### ISSUE TITLE
com.fasterxml.jackson.databind.exc.InvalidFormatException

### ISSUE THREAD

**Issue by Ericsongyl** [opendx/server#1]
在执行单步测试用例时，报如下错误，请问是什么原因？
具体log如下：
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "开启uiautomator2 server成功,端口为:": not a valid Integer value
 at [Source: (PushbackInputStream); line: 1, column: 907] (through reference chain: com.fgnb.dto.ActionDTO["uiautomatorServerPort"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1548) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer._parseInteger(NumberDeserializers.java:522) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:474) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:452) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.4.jar:2.9.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072) ~[jackson-databind-2.9.4.jar:2.9.4]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235) ~[spring-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 55 common frames omitted

**Comment by Ericsongyl** [comment]
已经解决，是因为自己改动过，使得agent工程有个地方的sessionId和web工程中的sessionid写法不一致造成。

**Comment by Ericsongyl** [comment]
关闭了
